(function registerEnglishContent(global) {
  'use strict';

  const data = global.HSG_DATA = global.HSG_DATA || {};
  data.translations = data.translations || {};
  data.translations.en = Object.freeze({
    metaDescription: 'Discover Happy Seal Games and ZAR, our strategy game currently in development. Play the ZAR Alpha on itch.io.',
    ogDescription: 'Independent games, bold ideas, and plenty of fun. ZAR Alpha is now available on itch.io.',
    skip: 'Skip to content',
    brandName: 'Happy Seal Games <span aria-hidden="true">|</span> Indie Developer Team',
    brandHome: 'Happy Seal Games home page',
    navLabel: 'Main navigation',
    languageLabel: 'Language selection',
    themeToggle: 'Switch between light and dark theme',
    themeDay: 'DAY',
    themeNight: 'NIGHT',
    navAbout: 'About Us',
    navGames: 'Our Other Games',
    navContact: 'Contact',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    heroEyebrow: 'Happy Seal Games presents',
    heroTitle: '<span class="hero-title-line hero-title-primary">We make the games</span><span class="hero-title-line">we want to play.</span>',
    heroCopy: 'Happy Seal Games is a small independent game development studio based in Türkiye. We are currently working on <strong>ZAR</strong>, our first commercial project.',
    heroTry: 'Discover ZAR <span aria-hidden="true">↓</span>',
    heroDiscover: 'Meet the Studio <span aria-hidden="true">→</span>',
    nextSection: 'Go to studio information',
    heroAlt: 'Happy Seal Games logo',
    heroSticker: 'INDIE<br>STUDIO',
    aboutEyebrow: 'Who are we?',
    aboutTitle: '<span class="about-title-line">A small team that loves</span><span class="about-title-line">making and playing games.</span>',
    aboutLogoAlt: 'Happy Seal Games logo featuring a cheerful seal mascot',
    aboutLead: 'We turn fun ideas into games you want to come back to.',
    aboutBody: 'We aim to make games that are easy to play but hard to master, with replayability and fun at their heart.',
    aboutContact: 'Contact us <span aria-hidden="true">→</span>',
	studioPoint1Title: 'Indie Team',
	studioPoint1Body: 'A small team making games we love.',
    studioPoint2Title: 'Player focused',
    studioPoint2Body: 'Games shaped together with feedback.',
    studioPoint3Title: 'Always evolving',
    studioPoint3Body: 'A better experience with every release.',
    zarEyebrow: 'Our featured game',
    zarTitle: 'Every roll.<br>A new decision.',
    zarBody: 'ZAR is a physics-based 3D dice roguelike deckbuilder where every roll can change the course of your run. Combine dice, relics, and augments, build powerful synergies, and adapt to every challenge.',
    zarTags: '<span>3D</span><span>Physics</span><span>Roguelike</span><span>Deckbuilder</span><span>Strategy</span>',
    zarTagsLabel: 'ZAR genres',
    featuresLabel: 'ZAR features',
    feature1: '<span>01</span> Different dice, relics, and augments',
    feature2: '<span>02</span> Physics-based rolls and changing runs',
    feature3: '<span>03</span> An Alpha shaped by community feedback',
    playItch: 'Play the ZAR Alpha <span aria-hidden="true">↗</span>',
    alphaTrailerTitle: 'ZAR Alpha Trailer',
    watchFullGameplay: 'Watch Full Gameplay <span aria-hidden="true">↗</span>',
    zarCharacterAlt: "Sir Rollington, a playable character in ZAR",
    zarCharacterLabel: 'Sir Rollington',
    zarBlacksmithAlt: "ZAR's playable Blacksmith character",
    zarBlacksmithLabel: 'The Blacksmith',
    zarCharactersEyebrow: 'Meet the characters',
    zarBlacksmithBody: 'A master blacksmith who can uniquely forge every die.',
    zarSpeech: 'A master gambler who can manipulate luck',
    characterPrevious: 'Previous character',
    characterNext: 'Next character',
    zarGameplayEyebrow: 'How will you build your run?',
    zarGameplayTitle: 'Dice. Relics. Endless combinations.',
    zarGameplayAlt: 'ZAR gameplay screen',
    zarGameplayCaption: 'Throw your dice into the arena and turn the result into strategy.',
    zarLoadoutAlt: 'ZAR points and multiplier calculation',
    zarLoadoutCaption: 'Make points × multiplier greater to hit harder.',
    zarBuildsAlt: 'ZAR dice combinations',
    zarBuildsCaption: 'Build a different setup every run.',
    zarActiveSkillAlt: "A character's unique skill in ZAR",
    zarActiveSkillCaption: "Strengthen your combinations with each character's unique skill.",
    zarPhysicsAlt: 'Physics-based dice rolls in ZAR',
    zarPhysicsCaption: 'Every physical roll creates a new possibility.',
    steamAlt: 'ZAR coming soon to Steam banner',
    steamTitle: 'Getting ready for Steam!',
    updatesLabel: 'Steam and development plans',
    updatesPrevious: 'Previous update',
    updatesNext: 'Next update',
    updatesSteam: 'Coming soon to Steam',
    updatesRoadmap: 'Roadmap',
    updatesHint: 'Swipe between the Steam update and roadmap, or select one below.',
    studioLocation: 'Happy Seal Games, Türkiye',
    steamBody: "Try the early Alpha and help shape ZAR's future with your feedback.",
    roadmapEyebrow: "What's next?",
    roadmapTitle: 'ZAR Roadmap',
    roadmapBody: 'Open our development plan from Alpha to the Steam demo in a separate window.',
    roadmapOpen: 'Open the ZAR roadmap',
    roadmapButton: 'View the Roadmap <span aria-hidden="true">↗</span>',
    gamesEyebrow: 'The Happy Seal Games archive',
    gamesTitle: 'Our Other Games',
    gamesIntro: 'Explore our free projects, from game jam experiments to strategy games.',
    playOnItch: 'Play on itch.io <span aria-hidden="true">↗</span>',
    watchGameplay: 'Watch Gameplay',
    hoverToPreview: 'Hover or select to preview',
    tapToPreview: 'Show gameplay preview',
    tapToCover: 'Return to cover',
    pawsGenre: 'Bullet Hell · Action',
    pawsDescription: 'Fight clones that repeat your past movements before the simulation collapses. Learn their patterns, dash through attacks, and become your best self.',
    pawsAlt: 'Paws Inc. logo',
    pawsGameplayAlt: 'Paws Inc. gameplay preview',
    totomonGenre: 'Roguelike · Auto Battler',
    totomonDescription: 'Choose your Totomon team, enter automatic battles, and guide powerful mutation paths. Build synergies and become the greatest trainer.',
    totomonAlt: 'Totomon logo',
    totomonGameplayAlt: 'Totomon gameplay preview',
    collectorogueGenre: '3D · Roguelike',
    collectorogueDescription: 'Stack loot on an enchanted table to power an adventurer, then keep your setup intact when a chaotic cat scatters everything.',
    collectorogueAlt: 'Collectorogue logo',
    collectorogueGameplayAlt: 'Collectorogue gameplay preview',
    chickonautGenre: 'Action · Space',
    chickonautDescription: 'Manage your oxygen, mine Yolkium with a laser-equipped chick drone, and return to your ship in time to buy upgrades.',
    chickonautAlt: 'Chickonaut logo',
    chickonautGameplayAlt: 'Chickonaut gameplay preview',
    biscultGenre: 'Clicker · Idle',
    biscultDescription: 'Feed an endlessly hungry holy biscuit, expand resource production, gather followers, and run a wonderfully strange cult.',
    biscultAlt: 'Biscult logo',
    biscultGameplayAlt: 'Biscult gameplay preview',
    sylvaGenre: 'Tower Defense · Roguelike',
    sylvaDescription: 'Defend the sacred tree from endless insect waves by planting seeds, growing defensive plants, and preparing between attacks.',
    sylvaAlt: 'Sylva logo',
    sylvaGameplayAlt: 'Sylva gameplay preview',
    contactEyebrow: 'Stay connected',
    contactTitle: 'Reach us.',
    contactBody: 'Get in touch with questions, feedback, or collaboration proposals. Follow our channels for studio updates.',
    emailButton: 'Send an Email <span aria-hidden="true">↗</span>',
    formEyebrow: 'Write to us',
    formTitle: 'Send your message directly',
    formIntro: 'All fields except attachments are required. Enter your email address so we can reply.',
    formName: 'Your name or player nickname',
    formEmail: 'Your email address (required)',
    formSubject: 'Subject',
    formMessage: 'Your message',
    formAttachment: 'Add an image or file (optional)',
    formAttachmentHelp: 'PNG, JPG, WEBP, GIF, PDF, or TXT · 10 MB total maximum. For messages with files, complete verification on the FormSubmit page that opens.',
    formSubmit: 'Send Message',
    formSending: 'Sending…',
    formUploading: 'Opening FormSubmit… Complete verification to finish sending.',
    formSuccess: 'Your message has arrived. Thank you!',
    formError: 'The message could not be sent. Please try again or use the email link.',
    formTooLarge: 'Your attachments exceed the 10 MB total limit.',
    formPrivacy: 'Your message and email address are delivered to us through FormSubmit. We use your address to reply to you.',
    socialLabel: 'Social media links',
    emailLabel: 'Email',
    footerTagline: 'Happy seals.',
    backToTop: 'Back to top ↑',
    copyright: '© <span id="year"></span> Happy Seal Games. All rights reserved.'
  });
})(window);
