(function registerEnglishContent(global) {
  'use strict';

  const data = global.HSG_DATA = global.HSG_DATA || {};
  data.translations = data.translations || {};
  data.translations.en = Object.freeze({
    metaDescription: 'Discover Happy Seal Games and ZAR, our strategy game currently in development. Play the ZAR Alpha on itch.io.',
    ogDescription: 'Independent games, bold ideas, and plenty of fun. ZAR Alpha is now available on itch.io.',
    skip: 'Skip to content',
    brandName: 'Happy Seal Games <span aria-hidden="true">|</span> Indie Developer Team',
    brandHome: 'Happy Seal Games home page',
    navLabel: 'Main navigation',
    languageLabel: 'Language selection',
    navAbout: 'About Us',
    navGames: 'Our Other Games',
    navContact: 'Contact',
    navAlpha: 'Play the ZAR Alpha ↗',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    heroEyebrow: 'Happy Seal Games presents',
    heroTitle: 'We make<br><span>games.</span>',
    heroCopy: 'We turn bold ideas into playful, memorable game worlds with an independent spirit. We are currently developing ZAR, our physics-based, dice-driven 3D roguelike.',
    heroTry: 'Discover ZAR <span aria-hidden="true">↓</span>',
    heroDiscover: 'Meet the Studio <span aria-hidden="true">→</span>',
    heroAlt: 'Happy Seal Games logo',
    heroSticker: 'INDIE<br>STUDIO',
    aboutEyebrow: 'Who are we?',
    aboutTitle: 'Small team.<br>Big games.',
    aboutLogoAlt: 'Happy Seal Games logo featuring a cheerful seal mascot',
    aboutLead: 'Happy Seal Games is an independent game development team turning playful ideas into distinctive worlds.',
    aboutBody: 'We create experiences that are easy to learn, rewarding to master, and worth returning to. We continue building our first major adventure, ZAR, together with player feedback.',
    aboutContact: 'Contact us <span aria-hidden="true">→</span>',
    studioPoint1Title: 'Independent',
    studioPoint1Body: 'Our voice. Our worlds.',
    studioPoint2Title: 'Player focused',
    studioPoint2Body: 'Games shaped together with feedback.',
    studioPoint3Title: 'Always evolving',
    studioPoint3Body: 'A better experience with every release.',
    zarEyebrow: 'Our featured game',
    zarTitle: 'Every roll.<br>A new decision.',
    zarBody: 'ZAR is a physics-based 3D dice roguelike deckbuilder where every roll can change the course of your run. Combine dice, relics, and augments, build powerful synergies, and adapt to every challenge.',
    zarTags: '<span>3D Roguelike</span><span>Dice Builder</span><span>Physics</span><span>Strategy</span>',
    zarTagsLabel: 'ZAR genres',
    featuresLabel: 'ZAR features',
    feature1: '<span>01</span> Different dice, relics, and augments',
    feature2: '<span>02</span> Physics-based rolls and changing runs',
    feature3: '<span>03</span> An Alpha shaped by community feedback',
    playItch: 'Play the ZAR Alpha <span aria-hidden="true">↗</span>',
    zarCharacterAlt: "ZAR's suited main character",
    zarSpeech: 'Roll your dice. Build your combo. Change the run.',
    zarGameplayEyebrow: 'How will you build your run?',
    zarGameplayTitle: 'Dice. Relics. Endless combinations.',
    zarGameplayAlt: 'ZAR gameplay screen',
    zarGameplayCaption: 'Throw your dice into the physics-based arena and turn the result into strategy.',
    zarLoadoutAlt: 'ZAR points and multiplier calculation',
    zarLoadoutCaption: 'Make points × multiplier greater to hit harder.',
    zarBuildsAlt: 'ZAR dice combinations',
    zarBuildsCaption: 'Build a different setup every run.',
    zarRelicsAlt: 'ZAR relic system',
    zarRelicsCaption: 'Combine relics and multiply their effects.',
    zarPhysicsAlt: 'Physics-based dice rolls in ZAR',
    zarPhysicsCaption: 'Every physical roll creates a new possibility.',
    steamAlt: 'ZAR coming soon to Steam banner',
    steamTitle: 'Getting ready for Steam!',
    steamBody: "Try the early Alpha and help shape ZAR's future with your feedback.",
    roadmapEyebrow: "What's next?",
    roadmapTitle: 'ZAR Roadmap',
    roadmapBody: 'Open our development plan from Alpha to the Steam demo in a separate window.',
    roadmapOpen: 'Open the ZAR roadmap',
    roadmapButton: 'View the Roadmap <span aria-hidden="true">↗</span>',
    gamesEyebrow: 'The Happy Seal Games archive',
    gamesTitle: 'Check our other games',
    gamesIntro: 'Explore our free projects, from game jam experiments to strategy games.',
    playOnItch: 'Play on itch.io <span aria-hidden="true">↗</span>',
    watchGameplay: 'Watch Gameplay',
    hoverToPreview: 'Hover to preview gameplay',
    tapToPreview: 'Tap to preview gameplay',
    tapToCover: 'Tap to return to cover',
    pawsGenre: 'Bullet Hell · Action',
    pawsDescription: 'Fight clones that repeat your past movements before the simulation collapses. Learn their patterns, dash through attacks, and become your best self.',
    pawsAlt: 'Paws Inc. logo',
    pawsGameplayAlt: 'Paws Inc. gameplay preview',
    totomonGenre: 'Roguelike · Auto Battler',
    totomonDescription: 'Choose your Totomon team, enter automatic battles, and guide powerful mutation paths. Build synergies and become the greatest trainer.',
    totomonAlt: 'Totomon logo',
    totomonGameplayAlt: 'Totomon gameplay preview',
    collectorogueGenre: '3D · Roguelike',
    collectorogueDescription: 'Stack loot on an enchanted table to power an adventurer, then keep your setup intact when a chaotic cat scatters everything.',
    collectorogueAlt: 'Collectorogue logo',
    collectorogueGameplayAlt: 'Collectorogue gameplay preview',
    chickonautGenre: 'Action · Space',
    chickonautDescription: 'Manage your oxygen, mine Yolkium with a laser-equipped chick drone, and return to your ship in time to buy upgrades.',
    chickonautAlt: 'Chickonaut logo',
    chickonautGameplayAlt: 'Chickonaut gameplay preview',
    biscultGenre: 'Clicker · Idle',
    biscultDescription: 'Feed an endlessly hungry holy biscuit, expand resource production, gather followers, and run a wonderfully strange cult.',
    biscultAlt: 'Biscult logo',
    biscultGameplayAlt: 'Biscult gameplay preview',
    sylvaGenre: 'Tower Defense · Roguelike',
    sylvaDescription: 'Defend the sacred tree from endless insect waves by planting seeds, growing defensive plants, and preparing between attacks.',
    sylvaAlt: 'Sylva logo',
    sylvaGameplayAlt: 'Sylva gameplay preview',
    contactEyebrow: 'Stay connected',
    contactTitle: 'Something new<br>is coming!',
    contactBody: 'Follow us for ZAR updates, development notes, and news from the studio.',
    emailButton: 'Send an Email <span aria-hidden="true">↗</span>',
    formEyebrow: 'Write to us',
    formTitle: 'Send your message directly',
    formIntro: 'Reach us without opening an email app. You do not need to provide an email address.',
    formName: 'Your name or player nickname',
    formSubject: 'Subject',
    formMessage: 'Your message',
    formAttachment: 'Add an image or file (optional)',
    formAttachmentHelp: 'PNG, JPG, WEBP, GIF, PDF, or TXT · 10 MB total maximum',
    formSubmit: 'Send Message',
    formSending: 'Sending…',
    formSuccess: 'Your message has arrived. Thank you!',
    formError: 'The message could not be sent. Please try again or use the email link.',
    formTooLarge: 'Your attachments exceed the 10 MB total limit.',
    formPrivacy: 'Submitted information is processed through FormSubmit only to deliver your message to us.',
    socialLabel: 'Social media links',
    emailLabel: 'Email',
    footerTagline: 'Independent games. Bold ideas. Happy seals.',
    backToTop: 'Back to top ↑',
    copyright: '© <span id="year"></span> Happy Seal Games. All rights reserved.'
  });
})(window);
