(function registerTurkishContent(global) {
  'use strict';

  const data = global.HSG_DATA = global.HSG_DATA || {};
  data.translations = data.translations || {};
  data.translations.tr = Object.freeze({
    metaDescription: "Happy Seal Games ve geliştirme aşamasındaki strateji oyunu ZAR hakkında bilgi edinin. ZAR Alpha sürümünü itch.io üzerinden deneyin.",
    ogDescription: "Bağımsız oyunlar, güçlü fikirler ve bolca eğlence. ZAR Alpha şimdi itch.io'da.",
    skip: 'İçeriğe geç',
    brandName: 'Happy Seal Games <span aria-hidden="true">|</span> Indie Developer Team',
    brandHome: 'Happy Seal Games ana sayfa',
    navLabel: 'Ana menü',
    languageLabel: 'Dil seçimi',
    themeToggle: 'Açık veya koyu tema arasında geçiş yap',
    themeDay: 'GÜNDÜZ',
    themeNight: 'GECE',
    navAbout: 'Hakkımızda',
    navGames: 'Diğer Oyunlarımız',
    navContact: 'İletişim',
    menuOpen: 'Menüyü aç',
    menuClose: 'Menüyü kapat',
    heroEyebrow: 'Happy Seal Games sunar',
    heroTitle: 'Oynamak istediğimiz<br><span>oyunları yapıyoruz.</span>',
    heroCopy: "Happy Seal Games, Türkiye merkezli küçük bir bağımsız oyun geliştirme stüdyosudur. Şu anda ilk ticari projemiz olacak <strong>ZAR</strong> üzerinde çalışıyoruz.",
    heroTry: 'ZAR\'ı Keşfet <span aria-hidden="true">↓</span>',
    heroDiscover: 'Bizi Tanı <span aria-hidden="true">→</span>',
    nextSection: 'Stüdyo bilgilerine geç',
    heroAlt: 'Happy Seal Games logosu',
    heroSticker: 'BAĞIMSIZ<br>STÜDYO',
    aboutEyebrow: 'Biz kimiz?',
    aboutTitle: '<span class="about-title-line">Oyun yapmayı ve oynamayı seven </span><span class="about-title-line">küçük bir ekip</span>',
    aboutLogoAlt: 'Mutlu fok maskotlu Happy Seal Games logosu',
    aboutLead: 'Eğlenceli fikirleri tekrar dönüp oynamak isteyeceğin oyunlara dönüştürüyoruz.',
    aboutBody: 'Oynaması kolay ama ustalaşması zor; tekrar oynanabilirliğin ve eğlencenin ön planda olduğu oyunlar yapmayı hedefliyoruz.',
    aboutContact: 'Bize ulaş <span aria-hidden="true">→</span>',
    studioPoint1Title: 'Bağımsız ekip',
    studioPoint1Body: 'Sevdiğimiz oyunları yapan küçük bir ekibiz.',
    studioPoint2Title: 'Oyuncu odaklı',
    studioPoint2Body: 'Geri bildirimle birlikte gelişen oyunlar.',
    studioPoint3Title: 'Daima gelişen',
    studioPoint3Body: 'Her sürümde daha iyi deneyimler.',
    zarEyebrow: 'Öne çıkan oyunumuz',
    zarTitle: 'Her atış.<br>Yeni bir strateji.',
    zarBody: 'ZAR, her zar atışının önem taşıdığı; mümkün olan en az atışla en yüksek puana ulaşmaya çalıştığın, fiziğin önemli rol oynadığı bir roguelike deste oluşturma oyunudur. Farklı zar güçlendirmelerini, karakter yeteneklerini, eserleri ve el boyunca kazandığın birçok güçlendirmeyi etkili biçimde birleştirerek en yüksek skora ulaş!',
    zarTags: '<span>3D</span><span>Fizik</span><span>Roguelike</span><span>Deckbuilder</span><span>Strateji</span>',
    zarTagsLabel: 'ZAR türleri',
    featuresLabel: 'ZAR özellikleri',
    feature1: '<span>01</span> Farklı zarlar, eserler ve zar güçlendirmeleri',
    feature2: '<span>02</span> Fizik tabanlı atışlar ve her turda yeni olasılıklar',
    feature3: '<span>03</span> Topluluk geri bildirimiyle gelişen Alpha',
    playItch: 'ZAR Alpha\'yı Oyna <span aria-hidden="true">↗</span>',
    alphaAvailable: 'ŞİMDİ OYNANABİLİR',
    alphaPlayTitle: 'Zarları at. Alpha’ya katıl!',
    alphaPlayBody: 'ZAR henüz erken geliştirme aşamasında, ama oynamak için beklemene gerek yok. Alpha sürümünü şimdi itch.io üzerinden dene.',
    alphaPlayNote: 'Erken sürüm • Geliştirme devam ediyor',
    alphaTrailerTitle: 'ZAR Alpha Tanıtım Videosu',
    watchFullGameplay: 'Tam Oynanışı İzle <span aria-hidden="true">↗</span>',
    zarCharacterAlt: "ZAR'ın oynanabilir karakteri Sir Rollington",
    zarCharacterLabel: 'Sir Rollington',
    zarBlacksmithAlt: "ZAR'ın oynanabilir Demirci karakteri",
    zarBlacksmithLabel: 'Demirci',
    zarCharactersEyebrow: 'Oynanabilir karakterlerle tanış',
    characterComingSoon: 'Yakında',
    characterComingSoonBody: 'Yeni bir oynanabilir karakter yolda. Kim olduğunu yakında keşfedeceksin.',
    zarBlacksmithBody: 'Her zarı kendine özgü biçimde dövebilen usta bir demirci.',
    zarSpeech: 'Şansı yönlendirebilen usta bir kumarbaz.',
    characterPrevious: 'Önceki karakter',
    characterNext: 'Sonraki karakter',
    zarGameplayEyebrow: 'Bir sonraki tur için planın ne?',
    zarGameplayTitle: 'Farklı zarlar, eserler ve sonsuz ihtimal.',
    zarGameplayAlt: 'ZAR oynanış ekranı',
    zarGameplayCaption: 'Zarlarını arenaya at, çıkan sonucu stratejiye dönüştür.',
    zarLoadoutAlt: 'ZAR puan ve çarpan hesabı',
    zarLoadoutCaption: 'Daha yüksek hasar için puan × çarpan değerini artır.',
    zarBuildsAlt: 'ZAR zar kombinasyonları',
    zarBuildsCaption: 'Her turda farklı bir kombinasyon kur.',
    zarActiveSkillAlt: "ZAR'da bir karakterin benzersiz yeteneği",
    zarActiveSkillCaption: 'Her karakterin benzersiz yeteneğiyle kombinasyonlarını güçlendir.',
    zarPhysicsAlt: 'ZAR fizik tabanlı zar atışları',
    zarPhysicsCaption: 'Her yeni atış başka bir zincirleme etkiyi tetikleyebilir.',
    steamAlt: "ZAR yakında Steam'de bannerı",
    steamTitle: "Steam'e hazırlanıyoruz!",
    updatesLabel: 'Steam ve geliştirme planı',
    updatesPrevious: 'Önceki duyuru',
    updatesNext: 'Sonraki duyuru',
    updatesSteam: "Yakında Steam’de",
    updatesRoadmap: 'Yol haritası',
    updatesHint: 'Steam duyurusu ve yol haritası arasında kaydır veya aşağıdan seç.',
    studioLocation: 'Happy Seal Games, Türkiye',
    steamBody: "Erken Alpha'yı dene; geri bildiriminle ZAR'ın geleceğini şekillendir.",
    roadmapEyebrow: 'Sırada ne var?',
    roadmapTitle: 'ZAR yol haritası',
    roadmapBody: "Alpha'dan Steam demosuna uzanan geliştirme planımızı ayrı pencerede incele.",
    roadmapOpen: 'ZAR yol haritasını aç',
    roadmapButton: 'Yol Haritasını Aç <span aria-hidden="true">↗</span>',
    gamesEyebrow: 'Happy Seal Games arşivi',
    gamesTitle: 'Diğer Oyunlarımız',
    gamesIntro: 'Game jam deneylerinden strateji oyunlarına uzanan ücretsiz projelerimizi keşfet.',
    playOnItch: 'itch.io\'da Oyna <span aria-hidden="true">↗</span>',
    watchGameplay: 'Oynanışı İzle',
    hoverToPreview: 'Önizleme için üzerine gel veya seç',
    tapToPreview: 'Oynanış önizlemesini göster',
    tapToCover: 'Kapağa dön',
    pawsGenre: 'Bullet Hell · Aksiyon',
    pawsDescription: 'Simülasyon çökmeden önce geçmiş hareketlerini tekrarlayan klonlarına karşı savaş. Desenlerini öğren, saldırılardan sıyrıl ve en iyi sürümün ol.',
    pawsAlt: 'Paws Inc. logosu',
    pawsGameplayAlt: 'Paws Inc. oynanış görüntüsü',
    totomonGenre: 'Roguelike · Auto Battler',
    totomonDescription: 'Totomon takımını seç, otomatik savaşlara gir ve güçlü mutasyon yollarını yönet. Sinerjiler kurarak en büyük eğitmen ol.',
    totomonAlt: 'Totomon logosu',
    totomonGameplayAlt: 'Totomon oynanış görüntüsü',
    collectorogueGenre: '3D · Roguelike',
    collectorogueDescription: 'Büyülü masaya ganimet istifle, maceracıyı güçlendir ve ortalığı dağıtan kediye karşı düzenini koru.',
    collectorogueAlt: 'Collectorogue logosu',
    collectorogueGameplayAlt: 'Collectorogue oynanış görüntüsü',
    chickonautGenre: 'Aksiyon · Uzay',
    chickonautDescription: 'Oksijenini dikkatli kullan, lazerli civciv dronunla Yolkium çıkar ve geliştirmeler için gemine zamanında dön.',
    chickonautAlt: 'Chickonaut logosu',
    chickonautGameplayAlt: 'Chickonaut oynanış görüntüsü',
    biscultGenre: 'Clicker · Idle',
    biscultDescription: 'Açgözlü kutsal bisküvini besle; kaynak üretimini büyüt, takipçiler topla ve sınır tanımayan tuhaf bir kült yönet.',
    biscultAlt: 'Biscult logosu',
    biscultGameplayAlt: 'Biscult oynanış görüntüsü',
    sylvaGenre: 'Tower Defense · Roguelike',
    sylvaDescription: 'Kutsal ağacı bitmeyen böcek dalgalarına karşı savun; tohumları ek, bitkilerini geliştir ve saldırılara hazırlan.',
    sylvaAlt: 'Sylva logosu',
    sylvaGameplayAlt: 'Sylva oynanış görüntüsü',
    contactEyebrow: 'Bağlantıda kal',
    contactTitle: 'Bize ulaş.',
    contactBody: 'Soruların, geri bildirimlerin ve iş birliği tekliflerin için bize yaz. Gelişmeler için bizi sosyal medyada takip etmeyi unutma.',
    emailButton: 'E-posta Gönder <span aria-hidden="true">↗</span>',
    formEyebrow: 'Bize yaz',
    formTitle: 'Mesajını doğrudan gönder',
    formIntro: 'Dosya eki dışındaki tüm alanlar zorunlu. Sana yanıt verebilmemiz için e-posta adresini gir.',
    formName: 'Adın veya oyuncu nick\'in',
    formEmail: 'E-posta adresin (zorunlu)',
    formSubject: 'Konu başlığı',
    formMessage: 'Mesajın',
    formAttachment: 'Görsel veya dosya ekle (isteğe bağlı)',
    formAttachmentHelp: 'PNG, JPG, WEBP, GIF, PDF veya TXT · Toplam en fazla 10 MB. Dosyalı mesajlarda açılan FormSubmit sayfasındaki doğrulamayı tamamla.',
    formSubmit: 'Mesajı Gönder',
    formSending: 'Gönderiliyor…',
    formUploading: 'FormSubmit açılıyor… Gönderimi tamamlamak için doğrulamayı bitir.',
    formSuccess: 'Mesajın ulaştı. Teşekkürler!',
    formError: 'Mesaj gönderilemedi. Lütfen tekrar dene veya e-posta bağlantısını kullan.',
    formTooLarge: 'Eklerin toplam boyutu 10 MB sınırını aşıyor.',
    formPrivacy: 'Mesajın ve e-posta adresin FormSubmit üzerinden bize iletilir. Adresini sana yanıt vermek için kullanırız.',
    socialLabel: 'Sosyal medya bağlantıları',
    emailLabel: 'E-posta',
    footerTagline: 'Eğlenceli oyunlar, mutlu foklar.',
    backToTop: 'Yukarı dön ↑',
    copyright: '© <span id="year"></span> Happy Seal Games. Tüm hakları saklıdır.'
  });
})(window);
