(function registerTurkishContent(global) {
  'use strict';

  const data = global.HSG_DATA = global.HSG_DATA || {};
  data.translations = data.translations || {};
  data.translations.tr = Object.freeze({
    metaDescription: "Happy Seal Games ve geliştirme aşamasındaki strateji oyunu ZAR hakkında bilgi edinin. ZAR Alpha sürümünü itch.io üzerinden deneyin.",
    ogDescription: "Bağımsız oyunlar, güçlü fikirler ve bolca eğlence. ZAR Alpha şimdi itch.io'da.",
    skip: 'İçeriğe geç',
    brandName: 'Happy Seal Games <span aria-hidden="true">|</span> Indie Developer Team',
    brandHome: 'Happy Seal Games ana sayfa',
    navLabel: 'Ana menü',
    languageLabel: 'Dil seçimi',
    themeToggle: 'Açık veya koyu tema arasında geçiş yap',
    themeDay: 'GÜNDÜZ',
    themeNight: 'GECE',
    navAbout: 'Hakkımızda',
    navGames: 'Diğer Oyunlarımız',
    navContact: 'İletişim',
    menuOpen: 'Menüyü aç',
    menuClose: 'Menüyü kapat',
    heroEyebrow: 'Happy Seal Games sunar',
    heroTitle: 'Oyunlar<br><span>yapıyoruz.</span>',
    heroCopy: "Bağımsız ruhla, güçlü fikirleri eğlenceli ve unutulmaz oyun dünyalarına dönüştürüyoruz. Şu anda fizik tabanlı, zar odaklı 3D roguelike oyunumuz ZAR'ı geliştiriyoruz.",
    heroTry: 'ZAR\'ı Keşfet <span aria-hidden="true">↓</span>',
    heroDiscover: 'Bizi Tanı <span aria-hidden="true">→</span>',
    nextSection: 'Stüdyo bilgilerine geç',
    heroAlt: 'Happy Seal Games logosu',
    heroSticker: 'BAĞIMSIZ<br>STÜDYO',
    aboutEyebrow: 'Biz kimiz?',
    aboutTitle: 'Küçük ekip.<br>Büyük oyunlar.',
    aboutLogoAlt: 'Mutlu fok maskotlu Happy Seal Games logosu',
    aboutLead: 'Happy Seal Games, eğlenceli fikirleri kendine özgü dünyalara dönüştüren bağımsız bir oyun geliştirme ekibi.',
    aboutBody: 'Amacımız; kolay öğrenilen, ustalaşması keyifli ve oyuncuların tekrar dönmek isteyeceği deneyimler üretmek. İlk büyük maceramız ZAR için oyuncu geri bildirimleriyle birlikte çalışmaya devam ediyoruz.',
    aboutContact: 'Bize ulaş <span aria-hidden="true">→</span>',
    studioPoint1Title: 'Bağımsız',
    studioPoint1Body: 'Kendi sesimiz, kendi dünyalarımız.',
    studioPoint2Title: 'Oyuncu odaklı',
    studioPoint2Body: 'Geri bildirimle birlikte gelişen oyunlar.',
    studioPoint3Title: 'Daima gelişen',
    studioPoint3Body: 'Her sürümde daha iyi deneyimler.',
    zarEyebrow: 'Öne çıkan oyunumuz',
    zarTitle: 'Her atış.<br>Yeni bir karar.',
    zarBody: 'ZAR, her atışın koşunun yönünü değiştirebildiği fizik tabanlı bir 3D zar roguelike deckbuilder. Zarları, kalıntıları ve güçlendirmeleri birleştir; güçlü sinerjiler kur ve her mücadeleye uyum sağla.',
    zarTags: '<span>3D Roguelike</span><span>Dice Builder</span><span>Physics</span><span>Strategy</span>',
    zarTagsLabel: 'ZAR türleri',
    featuresLabel: 'ZAR özellikleri',
    feature1: '<span>01</span> Farklı zarlar, kalıntılar ve güçlendirmeler',
    feature2: '<span>02</span> Fizik tabanlı atışlar ve değişen koşular',
    feature3: '<span>03</span> Topluluk geri bildirimiyle gelişen Alpha',
    playItch: 'ZAR Alpha\'yı Oyna <span aria-hidden="true">↗</span>',
    zarCharacterAlt: "ZAR'ın takım elbiseli ana karakteri",
    zarSpeech: 'Zarlarını at. Kombinasyonunu kur. Koşuyu değiştir.',
    zarGameplayEyebrow: 'Koşunu nasıl kuracaksın?',
    zarGameplayTitle: 'Zarlar. Kalıntılar. Sonsuz kombinasyon.',
    zarGameplayAlt: 'ZAR oynanış ekranı',
    zarGameplayCaption: 'Zarlarını fizik tabanlı arenaya at ve sonucu stratejine dönüştür.',
    zarLoadoutAlt: 'ZAR puan ve çarpan hesabı',
    zarLoadoutCaption: 'Daha sert vurmak için puan × çarpan değerini büyüt.',
    zarBuildsAlt: 'ZAR zar kombinasyonları',
    zarBuildsCaption: 'Her koşuda farklı bir yapı kur.',
    zarRelicsAlt: 'ZAR kalıntı sistemi',
    zarRelicsCaption: 'Kalıntıları birleştir, etkileri katla.',
    zarPhysicsAlt: 'ZAR fizik tabanlı zar atışları',
    zarPhysicsCaption: 'Her fiziksel atış yeni bir olasılık yaratır.',
    steamAlt: "ZAR yakında Steam'de bannerı",
    steamTitle: "Steam'e hazırlanıyoruz!",
    steamBody: "Erken Alpha'yı dene; geri bildiriminle ZAR'ın geleceğini şekillendir.",
    roadmapEyebrow: 'Sırada ne var?',
    roadmapTitle: 'ZAR yol haritası',
    roadmapBody: "Alpha'dan Steam demosuna uzanan geliştirme planımızı ayrı pencerede incele.",
    roadmapOpen: 'ZAR yol haritasını aç',
    roadmapButton: 'Yol Haritasını Aç <span aria-hidden="true">↗</span>',
    gamesEyebrow: 'Happy Seal Games arşivi',
    gamesTitle: 'Diğer oyunlarımıza göz at',
    gamesIntro: 'Game jam deneylerinden strateji oyunlarına uzanan ücretsiz projelerimizi keşfet.',
    playOnItch: 'itch.io\'da Oyna <span aria-hidden="true">↗</span>',
    watchGameplay: 'Oynanışı İzle',
    hoverToPreview: 'Oynanışı görmek için üzerine gel',
    tapToPreview: 'Oynanışı görmek için dokun',
    tapToCover: 'Kapağa dönmek için dokun',
    pawsGenre: 'Bullet Hell · Aksiyon',
    pawsDescription: 'Simülasyon çökmeden önce geçmiş hareketlerini tekrarlayan klonlarına karşı savaş. Desenlerini öğren, saldırılardan sıyrıl ve en iyi sürümün ol.',
    pawsAlt: 'Paws Inc. logosu',
    pawsGameplayAlt: 'Paws Inc. oynanış görüntüsü',
    totomonGenre: 'Roguelike · Auto Battler',
    totomonDescription: 'Totomon takımını seç, otomatik savaşlara gir ve güçlü mutasyon yollarını yönet. Sinerjiler kurarak en büyük eğitmen ol.',
    totomonAlt: 'Totomon logosu',
    totomonGameplayAlt: 'Totomon oynanış görüntüsü',
    collectorogueGenre: '3D · Roguelike',
    collectorogueDescription: 'Büyülü masaya ganimet istifle, maceracıyı güçlendir ve ortalığı dağıtan kediye karşı düzenini koru.',
    collectorogueAlt: 'Collectorogue logosu',
    collectorogueGameplayAlt: 'Collectorogue oynanış görüntüsü',
    chickonautGenre: 'Aksiyon · Uzay',
    chickonautDescription: 'Oksijenini dikkatli kullan, lazerli civciv dronunla Yolkium çıkar ve geliştirmeler için gemine zamanında dön.',
    chickonautAlt: 'Chickonaut logosu',
    chickonautGameplayAlt: 'Chickonaut oynanış görüntüsü',
    biscultGenre: 'Clicker · Idle',
    biscultDescription: 'Açgözlü kutsal bisküvini besle; kaynak üretimini büyüt, takipçiler topla ve sınır tanımayan tuhaf bir kült yönet.',
    biscultAlt: 'Biscult logosu',
    biscultGameplayAlt: 'Biscult oynanış görüntüsü',
    sylvaGenre: 'Tower Defense · Roguelike',
    sylvaDescription: 'Kutsal ağacı bitmeyen böcek dalgalarına karşı savun; tohumları ek, bitkilerini geliştir ve saldırılara hazırlan.',
    sylvaAlt: 'Sylva logosu',
    sylvaGameplayAlt: 'Sylva oynanış görüntüsü',
    contactEyebrow: 'Bağlantıda kal',
    contactTitle: 'Yeni bir şey<br>yaklaşıyor!',
    contactBody: 'ZAR güncellemeleri, geliştirme notları ve stüdyodan haberler için bizi takip et.',
    emailButton: 'E-posta Gönder <span aria-hidden="true">↗</span>',
    formEyebrow: 'Bize yaz',
    formTitle: 'Mesajını doğrudan gönder',
    formIntro: 'E-posta uygulaması açmadan bize ulaş. Sana yanıt verebilmemiz için e-posta adresini gir.',
    formName: 'Adın veya oyuncu nick\'in',
    formEmail: 'E-posta adresin (zorunlu)',
    formSubject: 'Konu başlığı',
    formMessage: 'Mesajın',
    formAttachment: 'Görsel veya dosya ekle (isteğe bağlı)',
    formAttachmentHelp: 'PNG, JPG, WEBP, GIF, PDF veya TXT · Toplam en fazla 10 MB. Dosyalı mesajlarda açılan FormSubmit sayfasındaki doğrulamayı tamamla.',
    formSubmit: 'Mesajı Gönder',
    formSending: 'Gönderiliyor…',
    formUploading: 'FormSubmit açılıyor… Gönderimi tamamlamak için doğrulamayı bitir.',
    formSuccess: 'Mesajın ulaştı. Teşekkürler!',
    formError: 'Mesaj gönderilemedi. Lütfen tekrar dene veya e-posta bağlantısını kullan.',
    formTooLarge: 'Eklerin toplam boyutu 10 MB sınırını aşıyor.',
    formPrivacy: 'Mesajın ve e-posta adresin FormSubmit üzerinden bize iletilir. Adresini sana yanıt vermek için kullanırız.',
    socialLabel: 'Sosyal medya bağlantıları',
    emailLabel: 'E-posta',
    footerTagline: 'Bağımsız oyunlar. Güçlü fikirler. Mutlu foklar.',
    backToTop: 'Yukarı dön ↑',
    copyright: '© <span id="year"></span> Happy Seal Games. Tüm hakları saklıdır.'
  });
})(window);
